const createTasteProfile = (config) => ({
  name: config.name || 'Your Taste',
  source: config.source,
  descriptor: config.descriptor || null,
  preferences: {
    energy: config.energy || [0.3, 0.7],
    valence: config.valence || [0.3, 0.7],
    danceability: config.danceability || [0.3, 0.7],
    acousticness: config.acousticness || [0, 1],
    tempo: config.tempo || [80, 140],
    popularity: config.popularity || [30, 80],
    genres: config.genres || [],
  },
  referenceTracks: config.referenceTracks || [],
  audioFeatureAverages: config.audioFeatureAverages || null,
  topExamples: config.topExamples || null,
});

export const PREMADE_PROFILES = {
  'chill-study': createTasteProfile({
    name: 'Chill Study Vibes',
    source: 'preset',
    descriptor: 'Lo-Fi Study Specialist',
    genres: ['acoustic', 'ambient', 'chill'],
    energy: [0, 0.4],
    valence: [0.3, 0.7],
    danceability: [0.3, 0.6],
    acousticness: [0.4, 1],
    tempo: [60, 100],
    popularity: [40, 80],
    audioFeatureAverages: {
      acousticness: 0.7,
      danceability: 0.45,
      energy: 0.25,
      instrumentalness: 0.3,
      key: 5,
      liveness: 0.1,
      loudness: -15,
      mode: 0,
      speechiness: 0.04,
      tempo: 80,
      time_signature: 4,
      valence: 0.5,
    },
  }),
  'gym-hype': createTasteProfile({
    name: 'Gym Hype',
    source: 'preset',
    descriptor: 'High Intensity Warrior',
    genres: ['edm', 'hip-hop', 'dance'],
    energy: [0.7, 1.0],
    valence: [0.5, 1.0],
    danceability: [0.7, 0.95],
    tempo: [120, 180],
    popularity: [60, 100],
    audioFeatureAverages: {
      acousticness: 0.05,
      danceability: 0.82,
      energy: 0.88,
      instrumentalness: 0.05,
      key: 7,
      liveness: 0.15,
      loudness: -4,
      mode: 1,
      speechiness: 0.15,
      tempo: 150,
      time_signature: 4,
      valence: 0.75,
    },
  }),
  'indie-darling': createTasteProfile({
    name: 'Indie Darling',
    source: 'preset',
    descriptor: 'Alternative Aesthete',
    genres: ['indie', 'alternative', 'folk'],
    energy: [0.3, 0.6],
    valence: [0.3, 0.6],
    danceability: [0.4, 0.7],
    acousticness: [0.3, 0.8],
    popularity: [20, 60],
    audioFeatureAverages: {
      acousticness: 0.55,
      danceability: 0.55,
      energy: 0.45,
      instrumentalness: 0.15,
      key: 2,
      liveness: 0.12,
      loudness: -8,
      mode: 0,
      speechiness: 0.05,
      tempo: 110,
      time_signature: 4,
      valence: 0.45,
    },
  }),
  'pop-royalty': createTasteProfile({
    name: 'Pop Royalty',
    source: 'preset',
    descriptor: 'Mainstream Maven',
    genres: ['pop', 'dance-pop'],
    energy: [0.6, 0.9],
    valence: [0.6, 1.0],
    danceability: [0.6, 0.9],
    popularity: [80, 100],
    audioFeatureAverages: {
      acousticness: 0.1,
      danceability: 0.75,
      energy: 0.75,
      instrumentalness: 0,
      key: 9,
      liveness: 0.11,
      loudness: -5,
      mode: 1,
      speechiness: 0.08,
      tempo: 120,
      time_signature: 4,
      valence: 0.8,
    },
  }),
};

export { createTasteProfile };